name: Django CI/CD

on:
  push:
    branches: [ "master" ]

env:
  PYTHON_VERSION: "3.12"
  DJANGO_SETTINGS_MODULE: crm.settings

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        working-directory: ./crm
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run migrations
        working-directory: ./crm
        run: python manage.py migrate --noinput

      - name: Run tests
        working-directory: ./crm
        run: python manage.py test
